name: Destroy TF manually

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Are You Sure ?"
        default: "Yes"
env:
  TFPath: tf/02_infra
  
jobs:
  destroy:
    name: "Terraform destroy"
    runs-on: ubuntu-latest
    env:
      TF_VAR_PREFIX: "FORTINET-${{ github.run_id }}-${{ github.run_number }}"
      region: "eu-west-3"
      TF_VAR_USERNAME: "admin"
      TF_VAR_PASSWORD: "${{ secrets.PASSWORD }}"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }} #needed for AWS S3 backend 
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }} #needed for AWS S3 backend 
      TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY }} #needed for TF
      TF_VAR_secret_key: ${{ secrets.AWS_SECRET_KEY }} #needed for TF
      
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.1

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ env.TFPath }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ${{ env.TFPath }}
